config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  resources :lists do
    resources :posts
  end

  root 'lists#new'

end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, :to => :data

  validates_presence_of :data
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, :mount_on => :data_file_name

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, :mount_on => :data_file_name

  def url_content
    url(:content)
  end
end

app/models/list.rb
class List < ActiveRecord::Base
  has_many :posts, dependent: :destroy
  has_many :sublists, class_name: "List",
                          foreign_key: "parent_list_id", dependent: :destroy
 
  belongs_to :parent_list, class_name: "List"
  accepts_nested_attributes_for :sublists, reject_if: :all_blank, allow_destroy: true  
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :list
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]

  # GET /lists
  # GET /lists.json
  def index
    @lists = List.all
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
  end

  # GET /lists/new
  def new
    if params[:list_id]
      @sublist = List.find(params[:list_id]).sublists.new
    else
      @list = List.new
    end
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice: 'List was successfully created.' }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to @list, notice: 'List was successfully updated.' }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @parent_list ||= @list.parent_list
    @list.destroy
    respond_to do |format|
      if @parent_list.nil?
        format.html { redirect_to root_path, notice: 'List was successfully destroyed.' }        
      else
        format.html { redirect_to @parent_list, notice: 'List was successfully destroyed.' }
      end
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_params
      params.require(:list).permit(:name, sublists_attributes: [:id, :name, :parent_list_id, :_destroy] )
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :set_list

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = @list.posts.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = @list.posts.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to list_path(@list), notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to list_path(@list), notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to list_url(@list), notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    def set_list
      @list = List.find(params[:list_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content, :list_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def notice_message
    alert_types = { notice: :success, alert: :danger }

    close_button_options = { class: "close", "data-dismiss" => "alert", "aria-hidden" => true }
    close_button = content_tag(:button, "×", close_button_options)

    alerts = flash.map do |type, message|
      alert_content = close_button + message

      alert_type = alert_types[type.to_sym] || type
      alert_class = "alert alert-#{alert_type} alert-dismissable"

      content_tag(:div, alert_content, class: alert_class)
    end

    alerts.join("\n").html_safe
  end
end

app/helpers/lists_helper.rb
module ListsHelper
  def render_sublists(head)
    if head.sublists.exists?

      content_tag :ul do
        head.sublists.map do |sub|
          selected = 'active' if sub.id.to_s == params[:id]
          concat(
            content_tag(:li, link_to("- #{sub.name}", list_path(sub), class: selected) + render_sublists(sub))
          )
        end
      end

    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/common/_sidebar.html.erb
<!-- Sidebar -->
<div id="sidebar-wrapper">
  <ul class="sidebar-nav">
    <li class="sidebar-brand">
      <a href="/">
        SW wiki
      </a>
    </li>
    <% List.where(parent_list_id: nil).each do |head| %>
      <li>
        <% selected = 'active' if head.id.to_s == params[:id] %>
        <%= link_to "- #{head.name}", list_path(head), class: selected %>
        <%= render_sublists(head) %>
      </li>
    <% end %>                
  </ul>
</div>
<!-- /#sidebar-wrapper -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Swwiki</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div id="wrapper">
    <%= render 'common/sidebar' %>
    <!-- Page Content -->
    <div id="page-content-wrapper">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <%= notice_message %>
                    <div>
                      <a href="#menu-toggle" id="menu-toggle"><span class="fa fa-exchange" style="font-size: 20px; color: #41a06f;"></span></a>
                    </div>
                    <%= yield %>
                </div>
            </div>
        </div>
    </div>
    <!-- /#page-content-wrapper -->
  </div>

  <!-- Menu Toggle Script -->
  <script>
  $("#menu-toggle").click(function(e) {
      e.preventDefault();
      $("#wrapper").toggleClass("toggled");
  });
  </script>
</body>
</html>

app/views/lists/_form.html.haml
= simple_form_for(@list) do |f|

  = f.error_notification

  .form-inputs
    = f.input :name, label: false
    .links
      = link_to_add_association f, :sublists, 'data-association-insertion-node' => "#sublists", 'data-association-insertion-method' => "after" do
        %span.fa.fa-plus
        = I18n.t('lists.form.add_sublist')

    %h3= t '.sublists'
    %ul#sublists{ style: 'list-style: none;' }
      = f.simple_fields_for :sublists do |sublist|
        %li= render partial:'sublist_fields', locals: { f: sublist }


  .form-actions
    = f.button :submit
    = link_to 'Cancel', list_path(@list) if @list.persisted?

app/views/lists/_sublist_fields.html.haml
.nested-fields.row
  .col-sm-8
    = f.input :name, label: false
  .col-sm-4
    = link_to_remove_association "X", f

app/views/lists/edit.html.haml
%h1 Editing list

= render 'form'

app/views/lists/index.html.haml
%h1 Listing lists

%table
  %thead
    %tr
      %th Name
      %th ID
      %th Subs
      %th 

  %tbody
    - List.all.each do |list|    
      %tr
        %td= list.name
        %td= list.id
        %td
          - list.sublists.each do |sub|
            = sub.id
        %td= link_to 'Show', list
        %td= link_to 'Edit', edit_list_path(list)
        %td= link_to 'Destroy', list, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New List', new_list_path

app/views/lists/new.html.haml
%h1= t ".title"

= render 'form'

app/views/lists/show.html.haml
%h1.inline= @list.name
%span
  = link_to new_list_post_path(list_id: @list.id) do
    %span.fa.fa-plus
    = I18n.t('add_post')
  \|
  = link_to list_path(@list), :method => :delete, :data => { :confirm => 'Are you sure?' } do
    %span.glyphicon.glyphicon-trash
    = I18n.t('delete')
  \|
  = link_to edit_list_path(@list) do
    %span.fa.fa-plus
    = I18n.t('lists.form.add_sublist')
  %hr

- @list.posts.each do |po|
  %h3.inline= po.title
  %span.pull-right
    = link_to edit_list_post_path(@list, po) do
      %span.glyphicon.glyphicon-edit
      = I18n.t('posts.edit')
    \|
    = link_to list_post_path(@list, po), :method => :delete, :data => { :confirm => 'Are you sure?' } do
      %span.glyphicon.glyphicon-trash
      = I18n.t('posts.delete')
  %p= sanitize(po.content)
  %hr

app/views/posts/_form.html.haml
= simple_form_for ([@list,@post]) do |f|
  = f.error_notification

  .form-inputs
    = f.input :title
    = f.input :content, :as => :ckeditor, :input_html => { :ckeditor => {:toolbar => 'Full'} }
    = f.association :list, selected: @list.id

  .form-actions
    = f.button :submit
    = link_to 'Cancel', list_path(@list)

app/views/posts/edit.html.haml
%h1 Editing post

= render 'form'

app/views/posts/index.html.haml
%h1 Listing posts

%table
  %thead
    %tr
      %th Title
      %th Content
      %th List
      %th
      %th
      %th

  %tbody
    - @posts.each do |post|
      %tr
        %td= post.title
        %td= sanitize(post.content)
        %td= post.list
        %td= link_to 'Edit', edit_list_post_path(@list, post)
        %td= link_to 'Destroy', list_post_path(@list, post), :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Post', new_list_post_path(@list)

app/views/posts/new.html.haml
%h1 New post

= render 'form'

app/views/posts/show.html.haml
%p
  %b Title:
  = @post.title
%p
  %b Content:
  = sanitize(@post.content)
%p
  %b List:
  = @post.list.name

= link_to 'Edit', edit_list_post_path(@list, @post)
\|
= link_to :Back